### ISSUE TITLE
Deployment uses just Tar method

### ISSUE THREAD

**Issue by ufik** [erincinci/magepanel#27]
Even if you set up Default deploy method to Rsync, it will always deploy via TarGZ method.

**Comment by erincinci** [comment]
Thanks for the notice, actually default deploy method selection in setup page is just a dummy setting for now, it will be used in the upcoming environment editor UI feature. But for now deployment method should be included in the environment file of the project. Otherwise it will be defaulted to tar.gz by the magallanes project. (Example is given below. Fix is included in the develop branch for environment file template)

deployment:
  user: dummy
  from: ./
  to: /var/www/vhosts/example.com
  strategy: rsync
  ...

**Comment by ufik** [comment]
Okay then, thank you.
